create table APP.ADDRESS (
    ID INTEGER,
    LASTNAME VARCHAR(30),
    FIRSTNAME VARCHAR(30),
    MIDDLENAME VARCHAR(30),
    PHONE VARCHAR(20),
    EMAIL VARCHAR(30),
    ADDRESS1 VARCHAR(30),
    ADDRESS2 VARCHAR(30),
    CITY VARCHAR(30),
    STATE VARCHAR(30),
    POSTALCODE VARCHAR(20),
    COUNTRY VARCHAR(30)
);